###Listar equipos
GET http://localhost:1234/team

###Listar un equipo por id
GET http://localhost:1234/team/65f9bdf7bbed4db012e73660

###Crear equipo
POST http://localhost:1234/team
Content-Type: application/json

{       
    "name":"Quilmes",
    "city":"BS AS",
    "ligue":"Primera"
}

###Listar partidos
GET http://localhost:1234/match

###Listar partidos con query
GET http://localhost:1234/match?isFinished=true&league=Superliga&seasonYear=2024&matchDate=2


###Listar partidos de un  equipo con su ID
GET http://localhost:1234/match/team/6610eb45b4732e87b22d1e02


###Crear partido
POST http://localhost:1234/match
Content-Type: application/json

{   
    "homeTeamName": "Quilmes" ,
    "awayTeamName": "Globo",
    "league":"Primera",
    "seasonYear":"2024",
    "matchDate": 2
}


###Agregar estadistica del partido
PUT http://localhost:1234/match/660b8471282aa29ae8f28c44/result
Content-Type: application/json

{

  "goalsHome": 0,
  "goalsAway": 0,
  "stats": {
    "local": {
      "goals": 3,
      "offsides": 12,
      "yellowCards": 2,
      "redCards": 1,
      "corners": 6
    },
    "visitor": {
      "goals":0,
      "offsides": 3,
      "yellowCards": 3,
      "redCards":0,
      "corners": 1
    }
  }
}


###Estadisticas por media (pensando si excluyo los no finalizados)
GET http://localhost:1234/match/stats/65f9bdf7bbed4db012e73660


###Estadisticas por acumulado como pidio Dani
GET http://localhost:1234/match/statsAc/6637dbf7b2a2deab04a69a97

###Estadisticas por acumulado como pidio Dani por todos los equipos de UNA TEMPORADA
GET http://localhost:1234/match/team-stats/6637dbf7b2a2deab04a69a97



###Estadisticas por acumulado como pidio Dani y con queries
GET http://localhost:1234/match/statsAc/65f9bdf7bbed4db012e73660?matchesCount=10&homeOnly=true&awayOnly=true


### pueba
GET http://localhost:1234/match/statsAc/65f9bdf7bbed4db012e73660?statistic=goals&lowerLimit=3.5&upperLimit=8&matchesCount=10&homeOnly=true&awayOnly=true
 

### pueba amarillas
GET http://localhost:1234/match/statsAc/65f9bdf7bbed4db012e73660?statistic=yellowCards&lowerLimit=3.5&upperLimit=8&matchesCount=10&homeOnly=true&awayOnly=true

### pueba corners
GET http://localhost:1234/match/statsAc/65f9bdf7bbed4db012e73660?statistic=corners&lowerLimit=3.5&upperLimit=8&matchesCount=10&homeOnly=true&awayOnly=false
 

### pueba offsies
GET http://localhost:1234/match/statsAc/66177fb172829d524e420b4e?statistic=goals&lowerLimit=0.5&upperLimit=12.5&matchesCount=10&homeOnly=true&awayOnly=true

### pueba (UTILIZANDO EN CLIENTE)
GET http://localhost:1234/match/statsAc/65f9bdf7bbed4db012e73660?statistic=goals&lowerLimit=0.5&upperLimit=5.5&matchesCount=10&homeOnly=true&awayOnly=true&lessThan=false

### 3 , 3,    1 ,5 
###  _ ,_  , V  ,_ ,



### Ligas
GET http://localhost:1234/league

### Ligas DELETE
DELETE  http://localhost:1234/league/661217d53393d074bfad45bd

### Crear liga
POST http://localhost:1234/league
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoicHVjaG8iLCJyb2xlIjoiQWRtaW4iLCJpYXQiOjE3MTUwNTg1MjksImV4cCI6MTcxNTY2MzMyOX0.qbzzCbv0Vl61F36u0Crp4Koo4rSlmRGmLqb1jMQoU1c

{
  "name":"Prueba de zod",
  "country":"Arg"
}


### Temporada
GET http://localhost:1234/season/6644cd86a2c9d8e4bd202488

###Crear una nueva temporada
POST http://localhost:1234/season
Content-Type: application/json

{
  "leagueId": "6612ecc98b76b7a905ae8b3f",
  "year":"2024"

}

###Delete temporada
DELETE  http://localhost:1234/season




###USUARIOS
### Dar de alta usuario, SOLO ADMIN
POST http://localhost:1234/user/register
Content-Type: application/json
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiZGFuaWVsUHVjaG8tIiwiaWF0IjoxNzE0NDA0MTg3LCJleHAiOjE3MTUwMDg5ODd9.qtoXrLx_kgvHe8lfvBm4FRLhgjPqDn3aMT1JXNde6E4

{
  "username":"pucho",
  "password":"pucho",
  "role":"Admin"
}

###Get all users
GET http://localhost:1234/user

###Login
POST http://localhost:1234/user/login
Content-Type: application/json

{
  "username":"pucho",
  "password":"pucho"
}

###Cerrar sesión
GET http://localhost:1234/user/logout
Content-Type: application/json


###verificar token
POST http://localhost:1234/verify-token
Content-Type: application/json



###Obtener fechas de una season
GET  http://localhost:1234/fecha/66477315e620bf8d2d91fbcc

### Temporada
GET http://localhost:1234/season/66477315e620bf8d2d91fbcc